Client-side authentication
PolyHx/HxBuddy pull request #12
Opened 2022-07-20 06:22 UTC by hainsdominic

Tout l'auth pour le client side.

On a besoin d'authentication pour les participants afin qu'ils puissent avoir acces a des pages comme leurs équipes.

Dans ce PR il y a le AuthContext, Axios qui update son token, un navigator custom selon le role et plus encore :)

J'ai transféré les choses qui étaient dans `main.tsx` et je les ai mis dans `App.tsx`. On est pas supposé avoir plus qu'un component dans le `main.tsx`.

2022-07-20 06:22 UTC, hainsdominic commented
Je vous encourage a tester manuellement

2022-07-20 06:25 UTC, hainsdominic commented
Le .env a changé aussi. Si vous copiez le .env.example et vous le renommez .env ca devrait fonctionnet out of the box

2022-07-20 13:32 UTC, SenecalJF requested changes

2022-07-20 13:32 UTC, SenecalJF commented on packages/server/src/auth/auth.controller.ts
> +    }
typescript strictess mode here, faudrait avoir un return pour le catch , sinon le return type c'est user | undefined

2022-07-20 13:32 UTC, SenecalJF commented on packages/web/src/Router.tsx
> +            <Route path="/login" element={<Login />} />"
Enlever le " ici

2022-07-21 22:24 UTC, hainsdominic commented on packages/server/src/auth/auth.controller.ts
> +    }
j'ai delete la fonction on en a pas besoin

2022-07-21 22:27 UTC, SenecalJF commented
lgtm

2022-07-21 22:28 UTC, SenecalJF approved these changes
lgtm

2022-07-23 20:59 UTC, merged