Team Module
PolyHx/HxBuddy pull request #13
Opened 2022-07-23 06:26 UTC by kugiyasan

Pour commencer: ne pas merge svp :p

J'ai commencé à faire les routes pour les teams, pour l'instant on peut créer les teams et en joindre une avec `/team/<teamId>/join/<participantId>`

Il faudra écrire un guard qui s'assure que le participant fait parti de la team avant de l'update ou de la delete (en ce moment tout le monde peut faire ces actions)

Tester les nouvelles routes se fait relativement facilement avec postman, juste commencer par se login et sauver le token comme variable globale (il manque des routes, celles-ci peuvent facilement être identifiées avec swagger)

2022-07-23 21:09 UTC, kugiyasan commented
TODO: add a guard to findAll team
TODO inject ParticipantService instead of ParticipantModel in TeamService

2022-07-24 19:00 UTC, hainsdominic commented on packages/server/src/team/team.schema.ts
> +  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Team', unique: true })
Le id est généré automatiquement par mongoose, il est créé automatiquement

2022-07-26 15:43 UTC, hainsdominic commented
pret a merge la?

2022-07-26 15:48 UTC, hainsdominic requested changes

2022-07-26 15:48 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +  @UseGuards(JwtAuthGuard)
On va add des guards plus tard i guess?

2022-07-26 15:48 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
inutile?

2022-07-26 15:48 UTC, hainsdominic commented on packages/server/src/team/team.service.ts
> +    console.log({ team, teamId, userId });
enleve le console.log

2022-07-26 15:48 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +  @UseGuards(JwtAuthGuard)
nvm je viens de voir le service, nice

2022-07-26 15:48 UTC, hainsdominic commented on packages/server/types.ts
> +export type UserRole = 'participant' | 'admin';
pourquoi?

2022-07-26 18:13 UTC, kugiyasan commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
on a besoin du param id pour le `SelfParticipantAuthGuard`, mais t'as raison que c pas clair, je vais rajouter un commentaire

2022-07-26 18:16 UTC, kugiyasan commented on packages/server/types.ts
> +export type UserRole = 'participant' | 'admin';
Il va en falloir un, mais d'accord, je vais le retirer pour l'instant, on le rajoutera quand on implémentera un role admin

2022-07-26 18:19 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
Dans ce cas utilise pas req.user.id, utilise le id dans les params, meme si tu dois le transformer

2022-07-26 18:24 UTC, kugiyasan commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
Je parlais de ça avec JF, mais les id sont un peu mélangeants
Ici, on a userId dans le jwt et participantId dans les params, et changer l'un par l'autre change un peu la logique du code (ça va être plus facile à créer les /me routes si on se sert que du userId dans le jwt)

2022-07-26 18:26 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
si le id dans les params represente le userId, je pense que ca fait du sens que live on l'utilise. On le changera par la suite pour faire plus de sens

2022-07-26 18:28 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
on ouvrira un issue par rapport a ca

2022-07-26 18:47 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
so le id ici c'est le participantId ou le userId?

2022-07-26 18:49 UTC, hainsdominic commented on packages/server/src/team/team.service.ts
> +    return team !== null && team._id.toString() === teamId;
Tu peux utiliser ca a la place:

`return team?._id.toString() === teamId;`

Le `?` check pour null et provoque un false si team est null

2022-07-26 20:06 UTC, kugiyasan commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
`:id` est un participantID

2022-07-26 20:20 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
> +    @Param('id') _participantId: string,
ok cool, donc etant donne qu'on utilise le participant dans le service, tu peut utiliser ce id pour get le participant. Ca serait pas donc ideal de prendre ce id dans le service?

2022-07-27 01:19 UTC, hainsdominic commented on packages/server/src/team/team.controller.ts
>      @Param('id') _participantId: string,
je parlais d'utiliser ca

2022-07-27 01:41 UTC, merged